name: Check events

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-events:
    name: Check events
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: ./.github/actions/check
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v5
        with:
          message: 'Update data'
          add: 'data/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
